WITH inventory_category_map (
  name,
  brand,
  colour,
  size_or_serial,
  status_marker,
  used_location_text,
  workbook_category
) AS (
  VALUES
    ('Obital Sander', 'Dewalt', NULL, NULL, '2025-07-23 00:00:00', NULL, 'Tools'),
    ('Obital Sander', 'Dewalt', NULL, NULL, '2025-07-31 00:00:00', NULL, 'Tools'),
    ('Obital Sander', 'Dewalt', NULL, NULL, '2026-02-21 00:00:00', NULL, 'Tools'),
    ('Battery&Charger', 'Dewalt', NULL, NULL, '2025-07-23 00:00:00', NULL, 'Tools'),
    ('Spray', NULL, NULL, NULL, NULL, NULL, 'Tools'),
    ('Grinder', 'Makita', NULL, NULL, NULL, NULL, 'Tools'),
    ('Battery&Charger', 'Dewalt', NULL, NULL, '2025-07-31 00:00:00', NULL, 'Tools'),
    ('Paint Stripper', 'Diggers', NULL, '4L', NULL, NULL, 'Tools'),
    ('High Pressure', 'Karcher', 'K 5 Premium Full Control', NULL, NULL, NULL, 'Tools'),
    ('High Pressure', 'Karcher', 'Karcher G3000C Petrol', NULL, NULL, NULL, 'Tools'),
    ('Jigsaw 18mm 450w', 'Makita', NULL, NULL, NULL, NULL, 'Tools'),
    ('FestTools', 'FestTool', NULL, NULL, NULL, NULL, 'Tools'),
    ('Point works', 'Selley''s', 'Grey', '10L', NULL, NULL, 'Tools'),
    ('Point works', 'Selley''s', 'Jet Black', '10L', NULL, NULL, 'Tools'),
    ('WaterTite', 'Zinsser', NULL, '10L', NULL, NULL, 'Tools'),
    ('Sample', 'Dulux', 'Antique White USA', '100ml (sample)', NULL, NULL, 'Sample'),
    ('Sample', 'Dulux', 'Natural White', '100ml (sample)', NULL, NULL, 'Sample'),
    ('Sample', 'Dulux', 'Grand Piano Quarter', '100ml (sample)', NULL, NULL, 'Sample'),
    ('Sample', 'Dulux', 'Beige Royal Quarter', '100ml (sample)', NULL, NULL, 'Sample'),
    ('Sample', 'Dulux', 'Hog Bristle Half', '100ml (sample)', NULL, NULL, 'Sample'),
    ('Texture', 'Dulux', 'Mideium', '10L', 'out', NULL, 'Primer'),
    ('Sealer Binder', 'Dulux', 'White', '4L', NULL, NULL, 'Primer'),
    ('WoodBlend', 'Intergrain', NULL, NULL, NULL, NULL, 'Primer'),
    ('Norglass Primer', 'Dulux', 'Black', '4L(3l)', NULL, NULL, 'Primer'),
    ('Peel Stop', 'Zinsser', 'Water-base Clear', '3.78L', NULL, NULL, 'Primer'),
    ('Cover Stain', 'Zinsser', NULL, '20L', NULL, NULL, 'Primer'),
    ('Bin', 'Zinsser', NULL, '3.78L', NULL, NULL, 'Primer'),
    ('All Metal Primer', 'Dulux', 'Light Grey', '4L', NULL, NULL, 'Primer'),
    ('Metal etch primer', 'Dulux', 'Light Grey', '3L (4L can)', NULL, NULL, 'Primer'),
    ('Dura Max', 'Dulux', 'appliance white', NULL, NULL, NULL, 'Primer'),
    ('Dura Max', 'Dulux', 'metal primer', NULL, NULL, NULL, 'Primer'),
    ('Pot Belly Black', 'White Knight', 'Primer', NULL, NULL, NULL, 'Primer'),
    ('Pot Belly Black', 'White Knight', 'Primer', '500ml', NULL, NULL, 'Primer'),
    ('Floetrol', 'Flood', 'Stain conditioner', '4L', NULL, NULL, 'Primer'),
    ('Zinsser', 'Zinsser', NULL, '4L (?)', 'out', NULL, 'Primer'),
    ('Ultra Pave', 'White Knight', 'white', '4L', NULL, NULL, 'Primer'),
    ('Acratex Roof Sealer (WB)', 'Dulux', 'Clear', '10L', 'out', NULL, 'Primer'),
    ('1 Step primer (water-based)', 'Dulux', 'White', '8L', 'out', NULL, 'Primer'),
    ('Total Prep', 'Dulux', 'white', '15L', 'out', NULL, 'Primer'),
    ('Norglass shipshape 2 pack epoxy', 'Norglass', 'white', '3L', NULL, NULL, 'Primer'),
    ('Norglass - Norclean', 'Norglass', 'Clear', '2.5L (4L can)', 'out', NULL, 'Primer'),
    ('Metal Etch Cleaner (Gel)', 'Norglass', 'Gel', '1L', NULL, NULL, 'Primer'),
    ('Metal Etch Cleaner (Gel)', 'Norglass', 'Gel', '4L', NULL, NULL, 'Primer'),
    ('Cabothane Clear(WB)', 'Cabot''s', 'Stain', '1L', 'out', NULL, 'Varnish'),
    ('Stain & Varnish(WB)', 'Cabot''s', 'Cedar stain', '1.5L', 'out', NULL, 'Varnish'),
    ('Deck&Exterior Stain (WB)', 'Cabot''s', 'Merbau', '4L', NULL, NULL, 'Varnish'),
    ('Ultra Clear', 'Intergrain', 'Stain', '1L', NULL, NULL, 'Varnish'),
    ('Ultra Deck (WB)', 'Intergraim', 'Natural', '4L', 'Eric', NULL, 'Varnish'),
    ('Kitchen&Bath ceiling', 'Dulux', 'white', '14L', 'out', NULL, 'Ceiling'),
    ('Kitchen&Bath ceiling', 'Dulux', 'white', '10L', NULL, NULL, 'Ceiling'),
    ('Ceiling White', 'Dulux', 'white', '10L', NULL, NULL, 'Ceiling'),
    ('Ceiling White', 'Dulux', 'white', '1L', 'out', NULL, 'Ceiling'),
    ('Pro Ceiling', 'Dulux', 'white', '15L', NULL, NULL, 'Ceiling'),
    ('Weathershield', 'Dulux', 'Domino (low)', '10L', NULL, NULL, 'Weathershield'),
    ('Weathershield', 'Dulux', 'Lexicon Half (semi)', '2L', NULL, NULL, 'Weathershield'),
    ('Weathershield', 'Dulux', 'white on white (semi)', '12L', NULL, NULL, 'Weathershield'),
    ('Weathershield', 'Dulux', 'Vivid white (low)', '4L', NULL, NULL, 'Weathershield'),
    ('Weathershield', 'Dulux', 'Vivid white (low)', '7.5L', NULL, NULL, 'Weathershield'),
    ('Weathershield', 'Dulux', 'Woodland grey (semi)', '10L', NULL, NULL, 'Weathershield'),
    ('Weathershield', 'Dulux', 'Monument (low)', '15L', 'out', '07/May Manly', 'Weathershield'),
    ('Weathershield', 'Dulux', 'Lexicon quarter (semi)', '2L', 'out', NULL, 'Weathershield'),
    ('Weathershield', 'Dulux', 'Natural white(low)', '7.5L', 'out', NULL, 'Weathershield'),
    ('Weathershield', 'Dulux', 'Lexicon quarter (low)', '14L', 'out', NULL, 'Weathershield'),
    ('Weathershield', 'Dulux', 'Lexicon quarter (Semi)', '13L', NULL, NULL, 'Weathershield'),
    ('Weathershield', 'Dulux', 'Natural white(low)', '2L', NULL, NULL, 'Weathershield'),
    ('Weathershield', 'Dulux', 'Natural white(low)', '7.5L', 'out', NULL, 'Weathershield'),
    ('Acratex (Acrashield)', 'Dulux', 'Rialto (Deep tone base)', '12L', NULL, NULL, 'Acratex'),
    ('Acratex (Acrashield)', 'Dulux', 'Dune', '13L', NULL, NULL, 'Acratex'),
    ('Acrarex roof sealer', 'Dulux', 'Water Base (Clear)', '2L (15L can)', 'out', NULL, 'Acratex'),
    ('Acratex acra prime 501', 'Dulux', 'Clear', '15L', NULL, NULL, 'Acratex'),
    ('Acratex acrashield advance', 'Dulux', 'vivid white', '15L', NULL, NULL, 'Acratex'),
    ('Aquanamel', 'Dulux', 'Caper white quarter (semi)', '7L', NULL, '20/Mar(Deborah)', 'Timber'),
    ('Aquanamel', 'Dulux', 'Natural White (semi)', '1L', 'out', NULL, 'Timber'),
    ('Aquanamel', 'Dulux', 'Lexicon quarter (semi)', '4L (10L can)', 'out', NULL, 'Timber'),
    ('Aquanamel', 'Dulux', 'Lexicon quarter (semi)', '2L (4L can)', 'out', NULL, 'Timber'),
    ('Aquanamel', 'Dulux', 'Lexicon quarter (semi)', '3L (4L can)', 'out', NULL, 'Timber'),
    ('Aquanamel', 'Dulux', 'Lexicon quarter (gloss)', '3L', NULL, NULL, 'Timber'),
    ('Superenamel', 'Dulux', 'White on white (gloss)', '2L (4L can)', NULL, NULL, 'Timber'),
    ('Aquanamel', 'Dulux', 'Vivid White (semi)', '3L (4L can)', 'out', '25/Mar (Bjorn)', 'Timber'),
    ('Superenamel', 'Dulux', 'Lexicon quarter (semi)', '3l', 'out', '23/Mar (Isabella)', 'Timber'),
    ('Superenamel', 'Dulux', 'Natural White (semi)', '3l', 'out', '08/May (rosvill)', 'Timber'),
    ('Aquanamel', 'Dulux', 'Lexicon quarter (semi)', '0.7L', 'out', NULL, 'Timber'),
    ('Metalshield Epoxy Enamel', 'Dulux', 'Colorbond Monument', '4L', 'out', NULL, 'Metalshield'),
    ('Metalshield epoxy enamel', 'Dulux', 'Black (stain)', '3L (4L can)', 'disposal', NULL, 'Metalshield'),
    ('Metalshield epoxy enamel', 'Dulux', 'Black (stain)', '3L (4L can)', 'disposal', NULL, 'Metalshield'),
    ('Metalshield epoxy enamel', 'Dulux', 'Domino (gloss)', '4L', 'disposal', NULL, 'Metalshield'),
    ('Metalshield epoxy enamel', 'Dulux', 'Vivid white (gloss)', '1L', 'disposal', NULL, 'Metalshield'),
    ('Professional inerior', 'Dulux', 'Natural white (lowsheen)', '15L + 12L?', 'out', NULL, 'Interior walls'),
    ('Professional inerior', 'Dulux', 'Lexicon quarter (lowsheen)', '15l', 'out', '23/Mar (Isabella)', 'Interior walls'),
    ('Wash & Wear', 'Dulux', 'Natural white (half)', '2L', NULL, NULL, 'Interior walls'),
    ('Professional inerior', 'Dulux', 'Snowy mountains (half)', '15L', NULL, NULL, 'Interior walls'),
    ('Professional inerior', 'Dulux', 'Lexicon (half)', '12L', NULL, NULL, 'Interior walls'),
    ('Wash & Wear (Kitchen & Bath)', 'Dulux', 'Lexicon quarter', '3L (4L can)', NULL, NULL, 'Interior walls'),
    ('Norglass weatherfast heat safe', 'Norglass', 'Black', '200ml', NULL, NULL, 'Special'),
    ('Durebild STE (2pack)', 'Dulux', 'Lexicon quarter', '3L (4L can)', 'out', NULL, 'Special')
)
UPDATE warehouse_inventory AS inventory
SET
  category = inventory_category_map.workbook_category,
  updated_at = now()
FROM inventory_category_map
WHERE inventory.source_year = '2026'
  AND inventory.active = true
  AND inventory.name = inventory_category_map.name
  AND coalesce(inventory.brand, '') = coalesce(inventory_category_map.brand, '')
  AND coalesce(inventory.colour, '') = coalesce(inventory_category_map.colour, '')
  AND coalesce(inventory.size_or_serial, '') = coalesce(inventory_category_map.size_or_serial, '')
  AND (
    inventory_category_map.used_location_text IS NULL
    OR coalesce(inventory.used_location_text, '') = inventory_category_map.used_location_text
  );

NOTIFY pgrst, 'reload schema';
